baseURL = "https://erik.dev/"
languageCode = "en-us"
title = "Erik St. Martin"
theme = "beautifulhugo"

metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "erikstmartin"

[Params]
  subtitle = "Linux, Kubernetes, Containers and infosec"
  logo = "img/erikdev-avatar.png"
  favicon = "img/gopher-favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  mainSections = ["post","posts"]

  [Author]
  name = "Erik St. Martin"
  website = "https:/erik.dev"
  email = "erik@erik.dev"
  googleplus = "+ErikStMartin"
  github = "erikstmartin"
  twitter = "erikstmartin"
  linkedin = "erikstmartin"
  youtube = "channel/UCZVEaATrwhATy2PIIOp442A"
  twitch = "ErikDotDev"
  mixer = "ErikDotDev"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "Minecraft"
    url = "minecraft"
    weight = 2

[[menu.main]]
    name = "Speaking"
    url = "speaking"
    weight = 3

[[menu.main]]
    name = "Podcasts"
    url = "podcasts"
    weight = 4


[[menu.main]]
    name = "About"
    url = "about"
    weight = 5

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 6